server:
  port: 8081
  logging:
    level:
      org.springframework.security: DEBUG
  servlet:
    encoding:
      charset: UTF8
      enabled: true
      force: true
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/exam?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true